apiVersion: v1
kind: Service
metadata:
  name: users-front
spec:
  selector:
    app: users-front
  ports:
    - port: 80        # Port interne du Service
      targetPort: 80  # Port du container (Nginx)
      nodePort: 30080 # Port exposé sur les nœuds (entre 30000-32767)
  type: NodePort
